/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'posaunehm' at '17/03/02 12:58' with Gradle 2.10
 *
 * @author posaunehm, @date 17/03/02 12:58
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
